const $=s=>document.querySelector(s);
const PAGE_URL={"Dashboard":"dashboard.html","Contacts":"contacts.html","Companies":"companies.html","Deals":"deals.html","Tasks":"tasks.html","Reports":"reports.html","Calendar":"calendar.html","Products":"products.html","Emails":"emails.html","Invoices":"invoices.html","Integrations":"integrations.html","Profile":"profile.html","Settings":"settings.html","Notifications":"notifications.html","Company detail":"company-detail.html","Deal detail":"deal-detail.html","Product detail":"product-detail.html","Edit contact":"edit-contact.html","Explore integrations":"explore-integrations.html","Import CSV":"import-csv.html","Add contact":"add-contact.html","Add company":"add-company.html","Add deal":"add-deal.html","Add product":"add-product.html","Add task":"add-task.html","Sign in":"sign-in.html","Sign up":"sign-up.html","Forgot password":"forgot-password.html","OTP verification":"otp-verification.html","New password":"new-password.html"};
const navUrl=n=>(location.pathname.endsWith('/index.html')?'html/':'')+(PAGE_URL[n]||('dashboard.html#'+encodeURIComponent(n)));
$("#nav").onclick=e=>{const n=e.target.closest(".nv");if(n)location.href=n.dataset.url};
document.querySelectorAll('#nav .nv').forEach(n=>{const active=n.dataset.p===document.body.dataset.page;n.classList.toggle('on',active);if(active)n.setAttribute('aria-current','page')});
$("#th").onchange=e=>setTh(e.target.value);
const col={Customer:"#5fae9a",Won:"#5fae9a",Paid:"#5fae9a",Completed:"#5fae9a",New:"#7FA6B8",Lead:"#7FA6B8",Partner:"#7FA6B8",Payment:"#7FA6B8",Qualified:"#8b8fc4",Proposal:"#c9a46a",Opportunity:"#c9a46a","Ex-Customer":"#c9a46a",Waiting:"#c9a46a",Pending:"#c9a46a",Lost:"#c96a6a",Competitor:"#c96a6a",Postponed:"#c96a6a",Overdue:"#c96a6a","To-Do":"#9ca3af"};
const pl=s=>`<span class="pl" style="--c:${col[s]||"#9ca3af"}">${s}</span>`;
const av=n=>`<span class="av" style="background:hsl(${[...n].reduce((a,c)=>a+c.charCodeAt(0)*7,0)%360} 55% 45%)">${n.split(" ").map(w=>w[0]).slice(0,2).join("")}</span>${n}`;
const D={
Contacts:[["Person name","Job title","Email","Phone","Owner","Status"],[["Ahmad Fauzi","Account Executive","ahmad@gmail.com","(+62) 80-0685-490","Ardian Maulana","Ex-Customer"],["Bayu Saputra","Account Manager","bayu@gmail.com","(+62) 81-2345-6789","Budi Santoso","Customer"],["Citra Maharani","Marketing Specialist","citra@gmail.com","(+62) 82-9876-5432","Clara Kusuma","Qualified"],["Daniel Susanto","Sales Executive","daniel@gmail.com","(+62) 81-0987-6543","Dewi Ayu Lestari","Opportunity"],["Erna Wijaya","Business Analyst","erna@gmail.com","(+62) 81-2345-0987","Eka Rahman","Customer"],["Oka Pratama","Marketing Manager","oka@gmail.com","(+62) 81-1122-2233","Gina Amelia","Lead"]],0,5],
Companies:[["Company","Address","Phone","URL","Owner","Type"],[["Amazon.com, Inc","1234 Innovation St","(+1) 408-996-1010","amazon.com","Budi Santoso","Ex-Customer"],["Apple, Inc","1 Infinite Loop","(+1) 650-681-5000","apple.com","Clara Kusuma","Competitor"],["Vodafone Group","Vodafone House","(+1) 425-882-8080","vodafone.com","Ardian Maulana","Partner"],["Ford Motor Company","World HQ","(+1) 312-555-4421","ford.com","Clara Kusuma","Customer"],["Tesla, Inc","3500 Deer Creek Rd","(+1) 415-800-5959","tesla.com","Dewi Ayu Lestari","Partner"]],0,5],
Deals:[["Deal name","Company","Price","Date created","Owner","Stage"],[["Cloud Infrastructure Migration","Amazon.com, Inc","$850,000.00","Mon, 12 Jan 2025","Ardian Maulana","New"],["Online Learning Platform","Shopify Inc","$420,000.00","Wed, 21 Jan 2025","Dwi Wahyu","Qualified"],["Retail POS System Upgrade","Best Buy Co.","$315,500.00","Fri, 30 Jan 2025","Adinda Ayu","Proposal"],["Brand Identity Redesign","Nike, Inc","$180,000.00","Tue, 04 Feb 2025","Galih Adi","Won"],["Travel Booking Integration","Traveloka","$96,000.00","Sat, 15 Feb 2025","Hendra K.","Payment"],["Pharmacy Inventory Suite","PharmaCare","$240,750.00","Thu, 27 Feb 2025","Maulana P.","Lost"]],4,5],
Tasks:[["Task name","Category","Due date","Team","Assignee","Status"],[["LAN optimization for client B","Network optimization","Tue, 20 Jan 2025","IT Operations team","Ardian Maulana","To-Do"],["IT maintenance contracts","Contract management","Mon, 26 Jan 2025","Marketing team","Budi Santoso","Waiting"],["Data breach investigation","Security","Wed, 21 Jan 2025","Development team","Clara Kusuma","Waiting"],["Managed IT services contract","Contract management","Sun, 01 Feb 2025","Technical team","Clara Kusuma","Completed"],["Network troubleshooting","Network support","Thu, 22 Jan 2025","Technical team","Eka Rahman","Postponed"]],0,5],
Products:[["Product name","Tags","Unit","Price","Code"],[["AWS Elastic Compute Cloud (EC2)","Operating System, Compute","Service","$23,000","GCI-001"],["Microsoft SQL Server Database","Cloud, Firewall","Service","$18,500","MSQ-002"],["Google Cloud Storage","Firewall, Database","Service","$7,000","GCS-003"],["Cisco Firewall Appliance","Cloud, Compute","Hardware","$12,200","CFA-004"],["Oracle Database 19c","Firewall, Azure","Service","$25,000","ODB-007"]],0,0],
Invoices:[["Invoice","Company","Amount","Due date","Status"],[["INV-2025-0142","Amazon.com, Inc","$850,000.00","12 Feb 2025","Paid"],["INV-2025-0141","Shopify Inc","$420,000.00","21 Feb 2025","Pending"],["INV-2025-0140","Best Buy Co.","$315,500.00","02 Feb 2025","Overdue"],["INV-2025-0139","Nike, Inc","$180,000.00","18 Jan 2025","Paid"]],0,4]};
const kpi=(t,v,d,c)=>`<div class="card"><span class="mu">${t}</span><div class="big">${v}</div><span style="color:${c||"#5fae9a"};font-weight:600">${d||""}</span></div>`;
const bars=(c)=>`<svg viewBox="0 0 200 50" width="100%" height="70" preserveAspectRatio="none">${[...Array(20)].map((_,i)=>`<rect class="bb" style="--i:${i}" x="${i*10}" y="${50-8-i*2}" width="7" height="${8+i*2}" rx="1.5" fill="${c}" opacity="${.3+i*.035}"/>`).join("")}</svg>`;
const sm=p=>p.reduce((s,[x,y],i)=>s+(i?`C${(p[i-1][0]+x)/2},${p[i-1][1]} ${(p[i-1][0]+x)/2},${y} ${x},${y}`:`M${x},${y}`),"");
const line=(sets)=>`<svg viewBox="0 0 800 260" width="100%">${[0,1,2,3,4].map(i=>`<line x1="0" x2="800" y1="${i*60+10}" y2="${i*60+10}" stroke="var(--bd)" stroke-dasharray="4"/>`).join("")}${sets.map(([c,a,d])=>`<path d="${sm(a.map((y,i)=>[i*800/(a.length-1),250-y*2.2]))}" fill="none" stroke="${c}" stroke-width="2.5" ${d?'stroke-dasharray="4 5"':""}/>`).join("")}</svg>`;
const table=(h,r,cp,cs,ck)=>`<div class="card tw"><table><tr><th><input type=checkbox>${h.map(x=>`<th>${x.toUpperCase()}`).join("")}${r.map(row=>`<tr><td><input type=checkbox>${row.map((c,i)=>`<td>${i==cs?pl(c):i==ck?av(c):i==cp?`<b>${c}</b>`:c}`).join("")}`).join("")}</table></div>`;
const tool=a=>`<div class="bar"><input class="in" placeholder="Search ${a.toLowerCase()}"><button class="b p" onclick="location.hash='Add ${a.toLowerCase()}'">+ Add ${a.toLowerCase()}</button></div><div class="bar"><button class="b">⇅ Sort by</button><button class="b">Filter</button><button class="b">List view</button><span style="flex:1"></span><button class="b">Import/Export</button></div>`;
const P={
Dashboard:()=>`<div class="tabs"><span class="on">Overview</span><span>Sales</span><span>Order</span><span>Report</span></div><div class="g g3">${kpi("Total sales","$28.500","↑ 10.2%")+bars("#7FA6B8")}`.replace(/(<\/div>)(<svg)/g,"$1$2")+``,
Contacts:0};
const FC=[["Profit margin","#8b8fc4",[11.5,13,16,18,21,23.5,25,23.5,26,24,22,21]],["Operating expenses","#c9a46a",[8,10,12,14,16,19,19.5,18,17,16,17,18]],["Sales revenue","#7FA6B8",[5,7,9,11,13,14.5,15,14,13,12,13,14]]],MO="Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),SRC=[["Website","6.848",55,"#4f7f96"],["Social Media","2.490",20,"#8b8fc4"],["Email","1.867",15,"#7FA6B8"],["Referral","1.245",10,"#5fae9a"]];
const fx=i=>50+i*730/11,fy=v=>260-v*8;
function fcMove(e){const r=e.currentTarget.getBoundingClientRect();let i=Math.round(((e.clientX-r.left)/r.width*800-50)/(730/11));i=Math.max(0,Math.min(11,i));const x=fx(i),px=x/800*r.width;$("#fcw").classList.add("on");$("#fcl").setAttribute("x1",x);$("#fcl").setAttribute("x2",x);FC.forEach(([n,c,a],k)=>{const o=$("#fc"+k);o.setAttribute("cx",x);o.setAttribute("cy",fy(a[i]))});const t=$("#fct");t.style.left=(i>7?px-14:px+14)+"px";t.style.transform=i>7?"translateX(-100%)":"none";t.innerHTML=`<b>${MO[i]}</b>`+FC.map(([n,c,a])=>`<div style="margin-top:6px"><span style="color:${c}">●</span> ${n}: <b>$${a[i].toFixed(1)}K</b></div>`).join("")}
P.Dashboard=()=>`<div style="display:flex;justify-content:space-between;flex-wrap:wrap;gap:12px;margin-bottom:18px"><div class="tabs" style="margin:0"><span class="on">Overview</span><span>Sales</span><span>Order</span><span>Report</span></div><div class="bar" style="margin:0"><button class="b">⚟ Filter</button><button class="b p">⭳ Export all</button></div></div>
<div class="g g3">${[["Total sales","$28.500","↑ 10.2%","#7FA6B8","$"],["Operating expenses","$18.200","↓ 5.75%","#c9a46a","▣"],["Gross profit","$22.500","↑ 8.55%","#5fae9a","↗"]].map(([t,v,d,c,i])=>`<div class="card"><div style="display:flex;justify-content:space-between;align-items:center"><span class="mu"><span class="ico" style="--c:${c}">${i}</span> ${t}</span><span class="mu">⋮</span></div><div class="big">${v} <span class="pl n" style="--c:${d[0]=="↓"?"#c96a6a":"#5fae9a"}">${d}</span></div>${bars(c)}<span class="mu">VS last week</span></div>`).join("")}</div>
<div class="g g2" style="margin:18px 0"><div class="card"><div style="display:flex;justify-content:space-between;align-items:center"><h3 style="margin:0">Revenue forecast</h3><span><select class="b"><option>▣ Monthly</option><option>Weekly</option><option>Yearly</option></select> <span class="mu">⋮</span></span></div><div id="fcw" style="position:relative;margin-top:10px"><svg viewBox="0 0 800 300" width="100%" style="display:block" onmousemove="fcMove(event)" onmouseleave="$('#fcw').classList.remove('on')">${[0,6,12,18,24,30].map(v=>`<line x1="50" x2="780" y1="${fy(v)}" y2="${fy(v)}" stroke="var(--bd)" stroke-dasharray="4"/><text x="0" y="${fy(v)+4}" font-size="11" style="fill:var(--mu)">$${v}K</text>`).join("")}${MO.map((m,i)=>`<text x="${fx(i)}" y="288" font-size="11" text-anchor="middle" style="fill:var(--mu)">${m}</text>`).join("")}<line id="fcl" x1="0" x2="0" y1="20" y2="260" stroke="var(--mu)" stroke-dasharray="3 3"/>${FC.map(([n,c,a],k)=>`<path class="ln" pathLength="1" stroke-dasharray="1" d="${sm(a.map((v,i)=>[fx(i),fy(v)]))}" fill="none" stroke="${c}" stroke-width="2.5" style="animation-delay:${k*.2}s"/>`).join("")}${FC.map(([n,c],k)=>`<circle class="fcc" id="fc${k}" r="5" fill="${c}" stroke="#fff" stroke-width="2"/>`).join("")}<rect width="800" height="300" fill="transparent"/></svg><div class="fct" id="fct"></div></div><div class="mu" style="display:flex;justify-content:center;gap:22px;border-top:1px solid var(--bd);margin-top:14px;padding-top:12px;flex-wrap:wrap">${FC.map(([n,c])=>`<span><span style="color:${c}">●</span> ${n}</span>`).join("")}</div></div>
<div class="card"><div style="display:flex;justify-content:space-between;align-items:center"><h3 style="margin:0">Source</h3><span><select class="b"><option>Contacts</option><option>Companies</option></select> <span class="mu">⋮</span></span></div><div style="position:relative;width:200px;margin:16px auto"><svg viewBox="0 0 42 42" style="transform:rotate(-90deg);display:block">${SRC.map(([n,v,p,c],i)=>`<circle class="dn" cx="21" cy="21" r="15.9" fill="none" stroke="${c}" stroke-width="5" pathLength="100" stroke-dasharray="${p} ${100-p}" stroke-dashoffset="${-SRC.slice(0,i).reduce((a,x)=>a+x[2],0)}" style="animation-delay:${i*.2}s"/>`).join("")}</svg><div style="position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center"><b style="font-size:24px">12.450</b><small class="mu">Total</small></div></div>${SRC.map(([n,v,p,c])=>`<div style="display:flex;justify-content:space-between;padding:6px 0"><span style="border-left:3px solid ${c};padding-left:10px">${n}</span><span><b>${v}</b> <span class="mu" style="margin-left:12px">${p}%</span></span></div>`).join("")}<button class="b" style="width:100%;margin-top:10px">View details</button></div></div>
<div class="bar" style="justify-content:space-between;align-items:center"><h3 style="margin:0">Table data sales</h3><div class="bar" style="margin:0"><input class="in" placeholder="Search data"><button class="b">⇅ Sort by</button><button class="b">Filter</button></div></div>${table(...D.Deals.slice(0,1),D.Deals[1],0,5,4)}`;
P.Reports=()=>`<div class="g g4">${kpi("Total Revenue","$142.8K","↑ 14.3% vs last period")+kpi("Deals Won","86","↑ 9.1% vs last period")+kpi("Conversion Rate","24.6%","↑ 3.5% vs last period")+kpi("Avg Deal Size","$3.4K","↓ 2.1% vs last period","#c96a6a")}</div><div class="card" style="margin-top:18px"><b>Revenue trend</b>${line([["#7FA6B8",[5,40,15,60,45,95,80]],["#5fae9a",[20,25,45,45,50,52,70],1]])}</div>`;
const DOW=["SUN","MON","TUE","WED","THU","FRI","SAT"],CT={Task:"#7FA6B8",Meeting:"#c9a46a",Deal:"#4f7f96","Project given":"#8b8fc4",Deadline:"#c96a6a","Project completion":"#5fae9a"};
const fd=d=>d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,0)+"-"+String(d.getDate()).padStart(2,0);
const off=n=>{const d=new Date();d.setDate(d.getDate()+n);return fd(d)};
const esc=s=>String(s).replace(/[&<>"]/g,c=>"&#"+c.charCodeAt(0)+";");
let CE;try{CE=JSON.parse(localStorage.getItem("ev"))}catch(e){}
CE=CE||[{id:1,t:"LAN optimization for client B",ty:"Task",d:off(2),o:"Ardian Maulana Aji"},{id:2,t:"Cloud Infrastructure Migration kickoff",ty:"Project given",d:off(0),o:"Ahmad Fauzi"},{id:3,t:"Quarterly account review",ty:"Meeting",d:off(4),o:"Budi Santoso"},{id:4,t:"Retail POS upgrade deadline",ty:"Deadline",d:off(6),o:"Dewi Ayu Lestari"},{id:5,t:"Brand Identity Redesign delivered",ty:"Project completion",d:off(12),o:"Galih Adi"},{id:6,t:"Corporate VPN expansion",ty:"Task",d:off(-3),o:"Dewi Ayu Lestari"}];
const sv=()=>{try{localStorage.setItem("ev",JSON.stringify(CE))}catch(e){}};
let C={y:new Date().getFullYear(),m:new Date().getMonth(),v:"Month",s:fd(new Date()),mo:0};
const evs=d=>CE.filter(e=>e.d==d),rc=()=>{$("#v").innerHTML=P.Calendar()};
const chip=e=>`<div class="mail" style="display:flex;gap:10px;align-items:flex-start"><div style="flex:1"><b>${esc(e.t)}</b><br><span class="mu">${e.d} · ${esc(e.o||"")}</span></div><span class="pl" style="--c:${CT[e.ty]}">${e.ty}</span><button class="b" style="padding:2px 8px" onclick="cDel(${e.id})">×</button></div>`;
function cSel(d){C.s=d;rc()}function cV(v){C.v=v;rc()}function cMo(x){C.mo=x;rc()}function cDel(id){CE=CE.filter(e=>e.id!=id);sv();rc()}
function cToday(){const d=new Date();C.s=fd(d);C.y=d.getFullYear();C.m=d.getMonth();rc()}
function cNav(n){if(C.v=="Month"){const d=new Date(C.y,C.m+n,1);C.y=d.getFullYear();C.m=d.getMonth()}else{const d=new Date(C.s+"T00:00");d.setDate(d.getDate()+n*(C.v=="Week"?7:1));C.s=fd(d);C.y=d.getFullYear();C.m=d.getMonth()}rc()}
function cSave(){const t=$("#et").value.trim();if(!t)return;const d=$("#ed").value||C.s;CE.push({id:Date.now(),t,ty:$("#ety").value,d,o:$("#eo").value});sv();C.s=d;C.y=+d.slice(0,4);C.m=+d.slice(5,7)-1;C.mo=0;rc()}
P.Calendar=()=>{const{y,m,v,s}=C,f=new Date(y,m,1),n=new Date(y,m+1,0).getDate(),td=fd(new Date()),sd=new Date(s+"T00:00");let body,ti;
if(v=="Month"){ti=f.toLocaleString("en",{month:"long",year:"numeric"});body=`<div class="cal">${DOW.map(d=>`<small class=mu>${d}</small>`).join("")}${"<div></div>".repeat(f.getDay())}${[...Array(n)].map((_,i)=>{const d=fd(new Date(y,m,i+1));return `<div class="${d==s?"t":""}" style="${d==td&&d!=s?"outline:1px solid var(--btn)":""}" onclick="cSel('${d}')">${i+1}<span class="dots">${evs(d).slice(0,4).map(e=>`<i style="background:${CT[e.ty]}"></i>`).join("")}</span></div>`}).join("")}</div>`}
else if(v=="Week"){const w=new Date(sd);w.setDate(w.getDate()-w.getDay());ti="Week of "+w.toLocaleDateString("en",{month:"short",day:"numeric",year:"numeric"});body=`<div class="g" style="grid-template-columns:repeat(7,minmax(90px,1fr));gap:6px;overflow-x:auto">${[...Array(7)].map((_,i)=>{const x=new Date(w);x.setDate(w.getDate()+i);const d=fd(x);return `<div class="card" style="padding:8px;cursor:pointer;${d==s?"border-color:var(--btn)":""}" onclick="cSel('${d}')"><small class="mu">${DOW[i]}</small><br><b>${x.getDate()}</b>${evs(d).map(e=>`<div style="font-size:11px;margin-top:4px;padding-left:5px;border-left:3px solid ${CT[e.ty]}">${esc(e.t)}</div>`).join("")}</div>`}).join("")}</div>`}
else{ti=sd.toLocaleDateString("en",{weekday:"long",month:"long",day:"numeric",year:"numeric"});body=evs(s).map(chip).join("")||'<p class="mu">No events on this day.</p>'}
const up=CE.filter(e=>e.d>=td&&e.d<=off(7)).sort((a,b)=>a.d<b.d?-1:1),so=evs(s);
return `<div style="display:flex;justify-content:space-between;align-items:flex-end;flex-wrap:wrap;gap:12px;margin-bottom:18px"><div><h2 style="margin:0">Calendar</h2><span class="mu">Track deadlines, project start dates, completions and meetings at a glance</span></div><div class="bar" style="margin:0"><div class="tabs" style="margin:0">${["Month","Week","Day"].map(x=>`<span class="${x==v?"on":""}" onclick="cV('${x}')">${x}</span>`).join("")}</div><button class="b p" onclick="cMo(1)">+ New event</button></div></div>
<div class="g g2"><div class="card"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px"><h3 style="margin:0">${ti}</h3><div class="bar" style="margin:0"><button class="b" onclick="cNav(-1)">‹</button><button class="b" onclick="cToday()">Today</button><button class="b" onclick="cNav(1)">›</button></div></div><div class="mu" style="margin-bottom:12px;font-size:12px">${Object.keys(CT).map(k=>`<span style="margin-right:12px"><span style="color:${CT[k]}">●</span> ${k}</span>`).join("")}</div>${body}</div>
<div class="card" style="padding:0;max-height:640px;overflow:auto"><div style="padding:16px 20px;display:flex;justify-content:space-between"><div><h3 style="margin:0">Upcoming activities</h3><span class="mu">Next 7 days</span></div><button class="b" onclick="cMo(1)">+</button></div>${up.map(chip).join("")||'<p class="mu" style="padding:0 20px">Nothing scheduled.</p>'}<div style="padding:16px 20px 0"><b>${sd.toLocaleDateString("en",{weekday:"short",month:"short",day:"numeric"})}</b></div>${so.map(chip).join("")||'<p class="mu" style="padding:0 20px 16px">No events on the selected day.</p>'}</div></div>
${C.mo?`<div class="md"><div class="card" style="width:420px;max-width:92vw"><h3>New event</h3><label>Title</label><input class="in" id="et" style="width:100%" placeholder="e.g. Website redesign deadline"><label>Type</label><select class="in" id="ety" style="width:100%">${Object.keys(CT).map(k=>`<option>${k}</option>`).join("")}</select><label>Date</label><input class="in" id="ed" type="date" style="width:100%" value="${s}"><label>Assigned to</label><input class="in" id="eo" style="width:100%" placeholder="Owner / team member"><br><br><button class="b p" onclick="cSave()">Save event</button> <button class="b" onclick="cMo(0)">Cancel</button></div></div>`:""}`};
P.Emails=()=>`<div class="g g2" style="grid-template-columns:1fr 2fr"><div class="card" style="padding:0">${[["Bayu Saputra","Marketing Campaign Brief","01 Jan 2025"],["Ahmad Fauzi","Proposal for partnership","02 Jan 2025"],["Citra Maharani","Product Launch Plan","30 Apr 2025"],["Daniel Susanto","Event Sponsorship Agreement","20 Jun 2025"]].map(m=>`<div class="mail"><b>${m[0]}</b> <small class="mu" style="float:right">${m[2]}</small><br>${m[1]}</div>`).join("")}</div><div class="card" style="text-align:center;padding-top:120px"><b>Oops, email not visible</b><p class="mu">Select the email you want to view first</p></div></div>`;
P.Integrations=()=>`<h3>Featured apps</h3><div class="g g3">${[["CrealBit","clearbit.com",1],["Zapier","zapier.com",1],["Make","make.com",0],["Asana","asana.com",1],["Stripe","stripe.com",0],["Dropbox","dropbox.com",0]].map(([n,u,o])=>`<div class="card"><b>${n}</b><br><small class="mu">${u}</small><p class="mu">Connect ${n} with your CRM for smoother workflows.</p><div style="display:flex;justify-content:space-between;align-items:center"><button class="b">View detail</button><div class="sw ${o?"on":""}" onclick="this.classList.toggle('on')"></div></div></div>`).join("")}</div>`;
P.Profile=()=>`<div class="card" style="max-width:760px"><h3>Personal information</h3><div class="g" style="grid-template-columns:1fr 1fr">${[["First name","Praveen"],["Last name","Gope"],["Email","kr.praveengope@gmail.com"],["Phone number","860 - 3380 - 5648"],["Role","CRM Manager"],["Timezone","(GMT+07:00) Jakarta"]].map(([l,v])=>`<div><label>${l}</label><input class="in" style="width:100%" value="${v}"></div>`).join("")}</div><br><button class="b p">Save changes</button></div>`;
const setTh=v=>{const r=document.documentElement;v=="system"?r.removeAttribute("data-theme"):r.dataset.theme=v;$("#th").value=v;try{localStorage.setItem("th",v)}catch(e){}};
const setAc=c=>document.documentElement.style.setProperty("--btn",c);
setTh((()=>{try{return localStorage.getItem("th")}catch(e){}})()||"system");
const fld=(l,v="",t="text")=>`<div><label>${l}</label><input class="in" style="width:100%" type="${t}" value="${v}" placeholder="${l}"></div>`;
const frm=(t,f,b="Save")=>`<div class="card" style="max-width:760px"><h3>${t}</h3><div class="g" style="grid-template-columns:1fr 1fr">${f.map(x=>fld(...x)).join("")}</div><br><button class="b p" onclick="history.back()">${b}</button> <button class="b" onclick="history.back()">Cancel</button></div>`;
const au=(t,s,f,b,l)=>`<div class="card" style="max-width:400px;margin:30px auto;text-align:center"><div class="logo">FlowDesk</div><h2>${t}</h2><p class="mu">${s}</p><div style="text-align:left">${f.map(x=>fld(...x)).join("")}</div><br><button class="b p" style="width:100%">${b}</button><p>${l.map(n=>`<a href="#${n}" style="color:var(--btn)">${n}</a>`).join(" · ")}</p></div>`;
const det=(t,s,r)=>`<div class="card"><div style="display:flex;justify-content:space-between"><h2 style="margin:0">${t}</h2>${pl(s)}</div><div class="g g3" style="margin-top:20px">${r.map(([k,v])=>`<div><small class="mu">${k}</small><br><b>${v}</b></div>`).join("")}</div></div>`;
const tg=(t,d,o)=>`<div class="card" style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px"><div><b>${t}</b><br><span class="mu">${d}</span></div><div class="sw ${o?"on":""}" onclick="this.classList.toggle('on')"></div></div>`;
P.Settings=()=>`<div class="card" style="margin-bottom:12px"><h3>Appearance</h3><p class="mu">Theme mode</p>${["light","dark","system"].map(m=>`<button class="b" onclick="setTh('${m}')" style="margin-right:8px;text-transform:capitalize">${m}</button>`).join("")}<p class="mu">Accent color</p>${["#2A3E4B","#7FA6B8","#4f7f96","#5fae9a","#a9c6d4"].map(c=>`<button class="sw2" style="background:${c}" onclick="setAc('${c}')"></button>`).join("")}</div>${tg("Email notifications","Receive deal and task updates",1)+tg("Two-factor authentication","Extra security for your account",0)+tg("Weekly report","Summary every Monday",1)}`;
P.Notifications=()=>`<div class="card" style="padding:0">${[["New deal assigned","Cloud Infrastructure Migration","2m ago"],["Task due soon","LAN optimization for client B","1h ago"],["Invoice overdue","INV-2025-0140 · Best Buy Co.","Yesterday"],["Email received","Bayu Saputra: Marketing Campaign Brief","2d ago"]].map(n=>`<div class="mail"><b>${n[0]}</b> <small class="mu" style="float:right">${n[2]}</small><br><span class="mu">${n[1]}</span></div>`).join("")}</div>`;
P["Company detail"]=()=>det("Amazon.com, Inc","Ex-Customer",[["Address","1234 Innovation St"],["Phone","(+1) 408-996-1010"],["URL","amazon.com"],["Owner","Budi Santoso"],["Deals","3 open"],["Revenue","$850,000.00"]]);
P["Deal detail"]=()=>det("Cloud Infrastructure Migration","New",[["Company","Amazon.com, Inc"],["Price","$850,000.00"],["Created","Mon, 12 Jan 2025"],["Owner","Ardian Maulana"],["Stage","New"],["Probability","40%"]]);
P["Product detail"]=()=>det("AWS Elastic Compute Cloud (EC2)","Customer",[["Code","GCI-001"],["Unit","Service"],["Price","$23,000"],["Tags","Operating System, Compute"],["Stock","Unlimited"],["Sold","128"]]);
P["Edit contact"]=()=>frm("Edit contact",[["Full name","Ahmad Fauzi"],["Job title","Account Executive"],["Email","ahmad@gmail.com","email"],["Phone","(+62) 80-0685-490"],["Owner","Ardian Maulana"],["Status","Customer"]],"Save changes");
P["Add contact"]=()=>frm("Add contact",[["Full name"],["Job title"],["Email","","email"],["Phone"],["Owner"],["Status"]]);
P["Add company"]=()=>frm("Add company",[["Company name"],["Address"],["Phone"],["URL"],["Owner"],["Type"]]);
P["Add deal"]=()=>frm("Add deal",[["Deal name"],["Company"],["Price"],["Date created","","date"],["Owner"],["Stage"]]);
P["Add product"]=()=>frm("Add product",[["Product name"],["Tags"],["Unit"],["Price"],["Product code"]]);
P["Add task"]=()=>frm("Add task",[["Task name"],["Category"],["Due date","","date"],["Team"],["Assignee"],["Status"]]);
P["Explore integrations"]=()=>P.Integrations();
P["Import CSV"]=()=>`<div class="card" style="max-width:640px;text-align:center;padding:50px"><div style="border:2px dashed var(--bd);border-radius:14px;padding:40px"><h3>Drop your CSV file here</h3><p class="mu">Contacts, companies or deals · max 10 MB</p><button class="b p">Choose file</button></div></div>`;
P["Sign in"]=()=>au("Sign in","Welcome back to FlowDesk",[["Email","","email"],["Password","","password"]],"Sign in",["Sign up","Forgot password"]);
P["Sign up"]=()=>au("Create account","Start your 20-day trial",[["Full name"],["Email","","email"],["Password","","password"]],"Sign up",["Sign in"]);
P["Forgot password"]=()=>au("Forgot password","We'll email you a reset code",[["Email","","email"]],"Send code",["OTP verification","Sign in"]);
P["OTP verification"]=()=>au("OTP verification","Enter the 6-digit code we sent",[["Code","","text"]],"Verify",["New password"]);
P["New password"]=()=>au("New password","Choose a strong password",[["New password","","password"],["Confirm password","","password"]],"Save password",["Sign in"]);
function go(){
  const route=decodeURIComponent(location.hash.slice(1));
  if(route && PAGE_URL[route]){location.replace(navUrl(route));return}
}
addEventListener("hashchange",go);go();

// Store demo records locally so they remain available between page visits.
try{const saved=JSON.parse(localStorage.getItem('clientra-records'));if(saved)Object.keys(D).forEach(k=>{if(saved[k])D[k][1]=saved[k]})}catch(e){}
const persist=()=>{try{localStorage.setItem('clientra-records',JSON.stringify(Object.fromEntries(Object.entries(D).map(([k,v])=>[k,v[1]]))))}catch(e){}};
function notify(message){document.querySelector('.toast')?.remove();const el=document.createElement('div');el.className='toast';el.setAttribute('role','status');el.textContent=message;document.body.append(el);setTimeout(()=>el.remove(),3500)}
const pageName=()=>decodeURIComponent(location.hash.slice(1))||document.body.dataset.page||'Dashboard';
const originalGo=go;
go=function(){originalGo();enhancePage()};
const menu=document.createElement('button');menu.className='b ic menu-toggle';menu.textContent='\u2630';menu.setAttribute('aria-label','Toggle navigation');menu.setAttribute('aria-expanded','false');document.querySelector('header').prepend(menu);
menu.onclick=()=>{const open=document.body.classList.toggle('nav-open');menu.setAttribute('aria-expanded',String(open))};
document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.body.classList.remove('nav-open');menu.setAttribute('aria-expanded','false')}});
document.addEventListener('click',e=>{if(document.body.classList.contains('nav-open')&&!e.target.closest('aside')&&!e.target.closest('.menu-toggle')){document.body.classList.remove('nav-open');menu.setAttribute('aria-expanded','false')}});
document.querySelectorAll('.nv').forEach(n=>{n.tabIndex=0;n.setAttribute('role','link');n.onkeydown=e=>{if(e.key==='Enter')location.href=n.dataset.url}});
document.querySelector('header .bar button').onclick=()=>location.href=navUrl('Notifications');
function exportRecords(){const p=pageName(),data=D[p]||D.Deals;const csv=[data[0],...data[1]].map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=p.toLowerCase()+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function enhancePage(){
 const p=pageName(),view=$('#v');document.body.classList.remove('nav-open');menu.setAttribute('aria-expanded','false');
 view.querySelectorAll('label').forEach((label,index)=>{const input=label.nextElementSibling;if(input&&input.matches('input,select,textarea')){input.id=input.id||'field-'+index;label.htmlFor=input.id}});
 const recordTable=view.querySelector('table');
 if(D[p]&&recordTable&&!recordTable.dataset.hydrated){
  const rows=[...recordTable.querySelectorAll('tr')].slice(1);
  const saved=D[p][1];
  const editableRows=rows.map(row=>[...row.querySelectorAll('td')].slice(1).map(cell=>{const copy=cell.cloneNode(true);copy.querySelectorAll('.av').forEach(a=>a.remove());return copy.textContent.trim()}));
  const extra=saved.slice(rows.length);
  D[p][1]=[...editableRows,...extra];
  extra.forEach(values=>{const row=recordTable.insertRow();const checkbox=row.insertCell();checkbox.innerHTML='<input type="checkbox" aria-label="Select record">';values.forEach(value=>{row.insertCell().textContent=value})});
  recordTable.dataset.hydrated='true';
 }
 view.querySelectorAll('input[placeholder^="Search"]').forEach(input=>{input.setAttribute('aria-label',input.placeholder);input.oninput=()=>view.querySelectorAll('table tr').forEach((r,i)=>{if(i)r.hidden=!r.textContent.toLowerCase().includes(input.value.toLowerCase())})});
 view.querySelectorAll('a[href^="#"]').forEach(a=>{a.href=navUrl(decodeURIComponent(a.getAttribute('href').slice(1)))});
 view.querySelectorAll('table').forEach(t=>{const all=t.querySelector('th input');if(all){all.setAttribute('aria-label','Select all records');all.onchange=()=>t.querySelectorAll('td input').forEach(c=>c.checked=all.checked)}t.querySelectorAll('td input').forEach(c=>c.setAttribute('aria-label','Select record'))});
 view.querySelectorAll('button').forEach(b=>{
 const label=b.textContent.trim();
 if(label.includes('Export'))b.onclick=exportRecords;
 else if(label.startsWith('+ Add'))b.onclick=()=>location.href=navUrl('Add '+({Contacts:'contact',Companies:'company',Deals:'deal',Tasks:'task',Products:'product',Invoices:'deal'}[p]||'contact'));
 else if(label.includes('Sort by'))b.onclick=()=>{const t=view.querySelector('table');if(!t)return;const rows=[...t.querySelectorAll('tr')].slice(1);const desc=b.dataset.desc==='true';rows.sort((a,c)=>(desc?-1:1)*a.textContent.trim().localeCompare(c.textContent.trim()));rows.forEach(r=>t.querySelector('tbody').append(r));b.dataset.desc=String(!desc)};
 else if(label.includes('Filter'))b.onclick=()=>{const t=view.querySelector('table');if(!t){notify('No filters available for this view');return}const statuses=[...new Set([...t.querySelectorAll('.pl')].map(s=>s.textContent.trim()))];const dialog=document.createElement('div');dialog.className='md';dialog.innerHTML='<div class="card"><h3>Filter by status</h3><select class="in"><option value="">All statuses</option>'+statuses.map(s=>'<option>'+esc(s)+'</option>').join('')+'</select><p><button class="b p">Apply</button> <button class="b">Cancel</button></p></div>';document.body.append(dialog);dialog.querySelector('button').onclick=()=>{const s=dialog.querySelector('select').value;t.querySelectorAll('tr').forEach((r,i)=>{if(i)r.hidden=!!s&&r.querySelector('.pl')?.textContent.trim()!==s});dialog.remove()};dialog.querySelectorAll('button')[1].onclick=()=>dialog.remove()};
 else if(label==='Import/Export')b.onclick=()=>location.href=navUrl('Import CSV');
 else if(label==='List view')b.onclick=()=>{view.querySelector('table')?.classList.toggle('compact');notify('List view selected')};
 else if(label==='View details')b.onclick=()=>location.href=navUrl('Contacts');
 else if(label==='View detail')b.onclick=()=>{const card=b.closest('.card');notify(card.querySelector('b').textContent+' integration selected')};
 });
 if(p.startsWith('Add ')||p==='Edit contact'){
 const type=p==='Edit contact'?'Contacts':{contact:'Contacts',company:'Companies',deal:'Deals',product:'Products',task:'Tasks'}[p.slice(4)];
 if(!type)return;
 const buttons=view.querySelectorAll('button');buttons[0].onclick=()=>{const inputs=[...view.querySelectorAll('input')];inputs.forEach(i=>i.required=true);if(inputs.some(i=>!i.reportValidity()))return;const row=inputs.map(i=>esc(i.value.trim()));if(p==='Edit contact')D[type][1][0]=row;else D[type][1].push(row);persist();location.href=navUrl(type)};
 buttons[1].onclick=()=>location.href=navUrl(type);
 }
 if(p==='Profile'){try{const profile=JSON.parse(localStorage.getItem('clientra-profile'));if(profile)view.querySelectorAll('input').forEach((i,k)=>i.value=profile[k]||'')}catch(e){}view.querySelector('button').onclick=()=>{localStorage.setItem('clientra-profile',JSON.stringify([...view.querySelectorAll('input')].map(i=>i.value)));notify('Profile saved')}}
 if(p==='Emails'){view.querySelectorAll('.mail').forEach(mail=>mail.onclick=()=>{view.querySelectorAll('.card')[1].innerHTML='<h3>'+esc(mail.childNodes[mail.childNodes.length-1].textContent)+'</h3><p class="mu">From: '+esc(mail.querySelector('b').textContent)+'</p><p>Hello Praveen,</p><p>Please review the latest project updates and share your feedback. We look forward to discussing the next steps with your team.</p><textarea class="in" style="width:100%;min-height:140px" aria-label="Reply" placeholder="Write a reply"></textarea><p><button class="b p" id="reply">Send reply</button></p>';$('#reply').onclick=()=>{if(view.querySelector('textarea').value.trim()){notify('Reply saved locally');view.querySelector('textarea').value=''}}})}
 if(['Sign in','Sign up','Forgot password','OTP verification','New password'].includes(p)){view.querySelector('button').onclick=()=>{const inputs=[...view.querySelectorAll('input')];inputs.forEach(i=>i.required=true);if(inputs.some(i=>!i.reportValidity()))return;if(p==='OTP verification'&&!/^\d{6}$/.test(inputs[0].value)){notify('Enter a six-digit code');return}if(p==='New password'&&inputs[0].value!==inputs[1].value){notify('Passwords must match');return}location.href=navUrl({'Sign in':'Dashboard','Sign up':'Dashboard','Forgot password':'OTP verification','OTP verification':'New password','New password':'Sign in'}[p])}}
 if(p==='Import CSV'){const picker=document.createElement('input');picker.type='file';picker.accept='.csv';picker.hidden=true;const type=document.createElement('select');type.className='in';type.setAttribute('aria-label','Record type');type.innerHTML=['Contacts','Companies','Deals','Tasks','Products','Invoices'].map(k=>'<option>'+k+'</option>').join('');view.querySelector('.card').prepend(type);view.append(picker);view.querySelector('button').onclick=()=>picker.click();picker.onchange=async()=>{const file=picker.files[0];if(!file)return;if(file.size>10*1024*1024){notify('Choose a file smaller than 10 MB');return}const rows=parseCSV(await file.text());const key=type.value;if(rows.length<2||rows[0].length!==D[key][0].length){notify('CSV columns must match: '+D[key][0].join(', '));return}const records=rows.slice(1).filter(r=>r.some(Boolean));if(records.some(r=>r.length!==D[key][0].length)){notify('Each row must contain all required columns');return}D[key][1].push(...records.map(r=>r.map(esc)));persist();location.href=navUrl(key)}}
 view.querySelectorAll('.tabs span').forEach(tab=>{if(!tab.hasAttribute('onclick')){tab.tabIndex=0;tab.onclick=()=>{if(p==='Dashboard'&&tab.textContent!=='Overview'){location.href=navUrl({Sales:'Deals',Order:'Invoices',Report:'Reports'}[tab.textContent]);return}tab.parentElement.querySelectorAll('span').forEach(s=>s.classList.toggle('on',s===tab))};tab.onkeydown=e=>{if(e.key==='Enter')tab.click()}}});
 if(['Companies','Deals','Products','Contacts'].includes(p))view.querySelectorAll('table tr').forEach((row,i)=>{if(!i)return;const name=row.querySelectorAll('td')[1];name.style.cursor='pointer';name.tabIndex=0;name.onclick=()=>location.href=navUrl({Companies:'Company detail',Deals:'Deal detail',Products:'Product detail',Contacts:'Edit contact'}[p]);name.onkeydown=e=>{if(e.key==='Enter')name.click()}});
}
removeEventListener('hashchange',originalGo);addEventListener('hashchange',go);go();

function parseCSV(text){const rows=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(field);field=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(field);rows.push(row);row=[];field=''}else field+=c}if(field||row.length){row.push(field);rows.push(row)}return rows}
