# Generated by Django 5.2.18 on 2026-10-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='kind',
            field=models.CharField(choices=[('lead', 'Lead'), ('ticket', 'Support ticket'), ('contact', 'Contact'), ('company', 'Company'), ('deal', 'Deal'), ('task', 'Task'), ('communication', 'Communication'), ('note', 'Support note'), ('document', 'Document metadata'), ('product', 'Product'), ('invoice', 'Invoice')], max_length=20),
        ),
    ]
